# Assignment 2

Harsh Kashyap

CSE4

101917088 

In [1]:
import numpy as np

1. Create an array of 10 fives

In [2]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2. Create an array of the integers from 10 to 50

In [3]:
array=np.arange(10,50,1)
print(array) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create an array of all the even integers from 10 to 50

In [4]:
array=np.arange(10,50,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


4. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
arr =  np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [7]:
arr = np.random.normal(0,1,25)
print(arr)

[-0.06797085 -0.34291192  0.52996612 -0.04365775  0.78260114  1.77254017
 -0.20438015  0.15706401  0.26182393 -0.4446168   0.42384318 -0.86059807
 -0.67101493 -1.56963141 -1.39243793  0.50135979  0.72200203  0.90037725
 -1.00093927 -0.63232165  0.82410453  0.35078276 -0.51989555 -2.55416991
  0.63487365]


6. Create the following array:
array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
0.99, 1. ])

In [9]:
arr = np.arange(0, 1.01, 0.01)
print(arr)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


7. Create an array of 20 linearly spaced points between 0 and 1

In [10]:
arr = np.linspace(0,1,20)
print(arr)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


8. Generate the following matrix, mat,
array([[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20],
[21, 22, 23, 24, 25]])
and extract the following using the indexing and slicing:
array([[12, 13, 14, 15],
[17, 18, 19, 20],
[22, 23, 24, 25]])
array([[ 2],
[ 7],
[12]])
Get the sum of all the values in mat
Get the sum of all the rows and columns in mat

In [11]:
arr =  np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
sliced= np.array([arr[2][1:],arr[3][1:],arr[4][1:]])
print(sliced)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [17]:
sliced= np.array([[arr[0][1]],[arr[1][1]],[arr[2][1]]])
print(sliced)

[[ 2]
 [ 7]
 [12]]


In [20]:
print("Row sum")
print(np.sum(arr,axis=1))

[ 15  40  65  90 115]


In [21]:
print("Column sum")
print(np.sum(arr,axis=1))

Column sum
[ 15  40  65  90 115]
